### ISSUE TITLE
ToastUI not working in 2020.3.1f1

### ISSUE THREAD

**Issue by riverole** [herbou/Unity_ToastUI#1]
I am getting an error when importing the ToastUI package: 

You are trying to replace or create a Prefab from the instance 'text' that references a missing script. This is not allowed.
Please change the script or remove it from the GameObject.

Then, when I try to use the Toast, I get this error:

NullReferenceException: Object reference not set to an instance of an object
EasyUI.Toast.ToastUI.Show (System.String text, System.Single duration, UnityEngine.Color color) (at Assets/Toast UI/Scripts/ToastUI.cs:46)
EasyUI.Toast.ToastUI.Init (System.String text, System.Single duration, EasyUI.Toast.ToastColor color) (at Assets/Toast UI/Scripts/ToastUI.cs:38)
EasyUI.Toast.Toast.Show (System.String text, System.Single duration, EasyUI.Toast.ToastColor color) (at Assets/Toast UI/Scripts/Toast.cs:34)

**Comment by riverole** [comment]
I got myself to work by creating a new Mesh Pro GUI Text object and substituting the text one. Do you have by any chance what would the properties of that object be? Like a screenshot or such? Thanks!

**Comment by herbou** [comment]
Thanks bro, I fixed it, no need to add TextMeshPro anymore :)
